apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockertest-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockertest-web
  template:
    metadata:
      labels:
        app: dockertest-web
    spec:
      containers:
      - name: dockertest-web
        image: jonanders/dockertest.web:v1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dockertest-web
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: dockertest-web
